version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/bentranter/turbo
    steps:
      - checkout

      - run: go get -t -d -v ./...
      - run: go test -race -v ./...
